## MAX CUT SDP relaxation
### Graph based on viewers rating movies
Here we solve the relaxed SDP to find the MAX cut in a graph. The goal is to find integral solution for $\gamma$-stable graphs

In [11]:
from algo import build_laplacian, solve_sdp, assignment_solution
from data_proc import build_a, build_graph, build_user_to_movies
import numpy as np

In [12]:
# fake data to illustrate the integral solution
W = np.array([[0,4,0,8],[4,0,0,2],[0,0,0,7],[8,2,7,0]])
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)

{'obj': 76.00000011979628, 'time': 0.0076138973236083984, 'cvxopt_sol': {'gap': 1.0930142936199193e-06, 'primal infeasibility': 2.422191871671932e-09, 'relative gap': 1.4381767075527133e-08, 'residual as primal infeasibility certificate': None, 'dual slack': 1.3267550541781866e-09, 's': <272x1 matrix, tc='d'>, 'dual infeasibility': 2.277358076017723e-10, 'y': <4x1 matrix, tc='d'>, 'dual objective': -76.00000052607633, 'residual as dual infeasibility certificate': None, 'iterations': 6, 'primal slack': 2.4034875355250986e-09, 'primal objective': -75.99999971351623, 'z': <272x1 matrix, tc='d'>, 'x': <10x1 matrix, tc='d'>, 'status': 'optimal'}, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]



#### we introduce a gamma perturbation for all edges

In [13]:
gamma = 2
W_gamma1 = gamma * W
L = build_laplacian(W_gamma1)
X = solve_sdp(L, triangle_inequalities=True)
print(X)

{'obj': 152.00000005534625, 'time': 0.011139869689941406, 'cvxopt_sol': {'gap': 5.447151342554877e-07, 'primal infeasibility': 9.322465633145176e-10, 'relative gap': 3.583652202335624e-09, 'residual as primal infeasibility certificate': None, 'dual slack': 4.2609461651751397e-10, 's': <272x1 matrix, tc='d'>, 'dual infeasibility': 5.4612646865435217e-11, 'y': <4x1 matrix, tc='d'>, 'dual objective': -152.00000025008302, 'residual as dual infeasibility certificate': None, 'iterations': 6, 'primal slack': 9.25047544395745e-10, 'primal objective': -151.99999986060948, 'z': <272x1 matrix, tc='d'>, 'x': <10x1 matrix, tc='d'>, 'status': 'optimal'}, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]



#### we introduce a gamma perturbation for only part of the edges

In [14]:
gamma = 2
# random boolean mask for which values will be changed
mask = np.random.randint(0,2,size=W.shape).astype(np.bool)

# random matrix the same shape of your data
r = gamma * W

# use your mask to replace values in your input array
W_gamma2 = W
W_gamma2[mask] = r[mask]
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)

{'obj': 76.0000001197963, 'time': 0.009101152420043945, 'cvxopt_sol': {'gap': 1.0930143004565403e-06, 'primal infeasibility': 2.4221920817818716e-09, 'relative gap': 1.4381767165482674e-08, 'residual as primal infeasibility certificate': None, 'dual slack': 1.3267550514153147e-09, 's': <272x1 matrix, tc='d'>, 'dual infeasibility': 2.277359545214055e-10, 'y': <4x1 matrix, tc='d'>, 'dual objective': -76.00000052607636, 'residual as dual infeasibility certificate': None, 'iterations': 6, 'primal slack': 2.4034876543278714e-09, 'primal objective': -75.99999971351623, 'z': <272x1 matrix, tc='d'>, 'x': <10x1 matrix, tc='d'>, 'status': 'optimal'}, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]



In [ ]:
# Simulated data: 3 movies rated by 3 users
W = np.array([[0,0,0,-2,0,0],[0,0,0,2,2.5,0],[0,0,0,0,-1,2.5],[-2,2,0,0,0,0],[0,2.5,-1,0,0,0],[0,0,2.5,0,0,0]])
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)

In [ ]:
# building the summary dictionary
summary_dictionary = build_user_to_movies('movielens.tsv')
# unpacking of the dictionary
users_to_movies = summary_dictionary['users_to_movies']
n_users = summary_dictionary['n_users']
n_movies = summary_dictionary['n_movies']
# reduce the graph size
k_users = 10
k_movies = 10

In [17]:
# building the rating matrix
a = build_a(n_users, k_users, n_movies, k_movies, users_to_movies)
# building the adjacency matrix
W = build_graph(k_users, k_movies, a)
# the laplacian of the graph
W = np.array([[0,0,0,-2,0,0],[0,0,0,2,2.5,0],[0,0,0,0,-1,2.5],[-2,2,0,0,0,0],[0,2.5,-1,0,0,0],[0,0,2.5,0,0,0]])
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)

{'obj': 28.000000020015825, 'status': 'optimal', 'cvxopt_sol': {'dual infeasibility': 8.199887731906276e-11, 'gap': 3.034008769089791e-07, 'z': <900x1 matrix, tc='d'>, 'status': 'optimal', 'residual as dual infeasibility certificate': None, 's': <900x1 matrix, tc='d'>, 'x': <21x1 matrix, tc='d'>, 'residual as primal infeasibility certificate': None, 'iterations': 7, 'primal slack': 2.767074420618146e-10, 'primal objective': -27.999999892570838, 'primal infeasibility': 2.7766644025418645e-10, 'relative gap': 1.083574564546622e-08, 'y': <6x1 matrix, tc='d'>, 'dual slack': 9.769756075005612e-11, 'dual objective': -28.000000147460813}, 'time': 0.02052593231201172}
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 

In [10]:
L

array([[ 9, -7, -1, -1],
       [-7, 12,  0, -5],
       [-1,  0,  1,  0],
       [-1, -5,  0,  6]])