## MAX CUT SDP relaxation
### Graph based on viewers rating movies
Here we solve the relaxed SDP to find the MAX cut in a graph. The goal is to find integral solution for $\gamma$-stable graphs

In [1]:
from algo import build_laplacian, solve_sdp, assignment_solution
from data_proc import build_a, build_graph, build_user_to_movies
import numpy as np

## Fake data to illustrate the integral solution
Easy max cut solution. 

In [2]:
W = np.array([[0,4,0,8],[4,0,0,2],[0,0,0,7],[8,2,7,0]])
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 2.4034875355250986e-09, 'residual as primal infeasibility certificate': None, 'iterations': 6, 'primal objective': -75.99999971351623, 'primal infeasibility': 2.422191871671932e-09, 'y': <4x1 matrix, tc='d'>, 'gap': 1.0930142936199193e-06, 'z': <272x1 matrix, tc='d'>, 'x': <10x1 matrix, tc='d'>, 'relative gap': 1.4381767075527133e-08, 'dual infeasibility': 2.277358076017723e-10, 's': <272x1 matrix, tc='d'>, 'dual slack': 1.3267550541781866e-09, 'residual as dual infeasibility certificate': None, 'dual objective': -76.00000052607633}, 'time': 0.02396106719970703, 'obj': 76.00000011979628, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]



In [3]:
# assignement
X_array=np.array(X)
assignement_X = assignment_solution(X_array)
print(assignement_X)

[ True False  True False]


#### We introduce a gamma perturbation for all edges

In [4]:
gamma = 2
W_gamma1 = gamma * W
L = build_laplacian(W_gamma1)
X = solve_sdp(L, triangle_inequalities=True)
print(X)
X_array=np.array(X)
assignement_X = assignment_solution(X_array)
print(assignement_X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 9.250475097309765e-10, 'residual as primal infeasibility certificate': None, 'iterations': 6, 'primal objective': -151.99999986060948, 'primal infeasibility': 9.32246396921122e-10, 'y': <4x1 matrix, tc='d'>, 'gap': 5.447151303842985e-07, 'z': <272x1 matrix, tc='d'>, 'x': <10x1 matrix, tc='d'>, 'relative gap': 3.583652176867274e-09, 'dual infeasibility': 5.4612646964815894e-11, 's': <272x1 matrix, tc='d'>, 'dual slack': 4.2609461606260837e-10, 'residual as dual infeasibility certificate': None, 'dual objective': -152.000000250083}, 'time': 0.007411956787109375, 'obj': 152.00000005534622, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]

[ True False  True False]


#### We introduce a gamma perturbation for only part of the edges

In [9]:
gamma = 2 # if gamma = 1000 it may not work depending of the mask
# random boolean mask for which values will be changed
mask = np.random.randint(0,2,size=W.shape).astype(np.bool)

# random matrix the same shape of the data
W = np.array([[0,4,0,8],[4,0,0,2],[0,0,0,7],[8,2,7,0]])
r = gamma * W

# use your mask to replace values in your input array
W_gamma2 = W
W_gamma2[mask] = r[mask]
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)
X_array=np.array(X)
assignement_X = assignment_solution(X_array)
print(assignement_X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 1.8075359469820296e-09, 'residual as primal infeasibility certificate': None, 'iterations': 6, 'primal objective': -113.99999976036472, 'primal infeasibility': 1.8216027378542246e-09, 'y': <4x1 matrix, tc='d'>, 'gap': 9.395974741139145e-07, 'z': <272x1 matrix, tc='d'>, 'x': <10x1 matrix, tc='d'>, 'relative gap': 8.242083123587793e-09, 'dual infeasibility': 1.2111130055865823e-10, 's': <272x1 matrix, tc='d'>, 'dual slack': 9.602938797574428e-10, 'residual as dual infeasibility certificate': None, 'dual objective': -114.00000044661529}, 'time': 0.007483959197998047, 'obj': 114.00000010349001, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00  1.00e+00]

[ True False  True False]


## Simulated data
Simulating a bipartite graph with viewers giving grades (between -2.5 and 2.5) to movies.

In [85]:
W = np.array([[0,0,0,-2,0,-0.5],[0,0,0,2,2.5,0],[0,0,0,0,-1,2.5],[-2,2,0,0,0,0],[0,2.5,-1,0,0,0],[-0.5,0,2.5,0,0,0]])
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
print(X)
X_array=np.array(X)
assignement_X = assignment_solution(X_array)
print(assignement_X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 7.100027210930522e-10, 'residual as primal infeasibility certificate': None, 'iterations': 7, 'primal objective': -25.999999614701746, 'primal infeasibility': 7.124636446423574e-10, 'y': <6x1 matrix, tc='d'>, 'gap': 7.780167147477235e-07, 'z': <900x1 matrix, tc='d'>, 'x': <21x1 matrix, tc='d'>, 'relative gap': 2.992372024143387e-08, 'dual infeasibility': 2.0973469423445813e-10, 's': <900x1 matrix, tc='d'>, 'dual slack': 4.2476880876434165e-11, 'residual as dual infeasibility certificate': None, 'dual objective': -26.000000268314857}, 'time': 0.023572921752929688, 'obj': 25.9999999415083, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 

#### We introduce a gamma perturbation for all edges

In [68]:
gamma = 2
W_gamma1 = gamma * W
L = build_laplacian(W_gamma1)
X = solve_sdp(L, triangle_inequalities=True)
print(X)
X_array=np.array(X)
assignement_X = assignment_solution(X_array)
print(assignement_X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 8.937061110484262e-10, 'residual as primal infeasibility certificate': None, 'iterations': 7, 'primal objective': -51.999999481690224, 'primal infeasibility': 8.968039948176268e-10, 'y': <6x1 matrix, tc='d'>, 'gap': 1.0574242167232863e-06, 'z': <900x1 matrix, tc='d'>, 'x': <21x1 matrix, tc='d'>, 'relative gap': 2.0335081293522263e-08, 'dual infeasibility': 1.404635499023509e-10, 's': <900x1 matrix, tc='d'>, 'dual slack': 6.28433872142255e-11, 'residual as dual infeasibility certificate': None, 'dual objective': -52.00000035785482}, 'time': 0.01899099349975586, 'obj': 51.99999991977252, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00 -1

#### We introduce a gamma perturbation for only one edge

In [87]:
gamma = 10 # if gamma = 1000 it may not work anymore
# random boolean mask for which values will be changed
W_gamma2 = np.array([[0,0,0,-2,0,-0.5*gamma],[0,0,0,2,2.5,0],[0,0,0,0,-1,2.5],[-2,2,0,0,0,0],[0,2.5,-1,0,0,0],[-0.5*gamma,0,2.5,0,0,0]])

In [88]:
L = build_laplacian(W_gamma2)
X = solve_sdp(L, triangle_inequalities=True)
print(X)
X_array=np.array(X)
assignement_X = assignment_solution(X_array)
print(assignement_X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 1.5811769734055775e-09, 'residual as primal infeasibility certificate': None, 'iterations': 7, 'primal objective': -23.999999140950628, 'primal infeasibility': 1.586657774226448e-09, 'y': <6x1 matrix, tc='d'>, 'gap': 1.8553303809509545e-06, 'z': <900x1 matrix, tc='d'>, 'x': <21x1 matrix, tc='d'>, 'relative gap': 7.73054353066725e-08, 'dual infeasibility': 3.348021845681186e-10, 's': <900x1 matrix, tc='d'>, 'dual slack': 1.5124042061070395e-10, 'residual as dual infeasibility certificate': None, 'dual objective': -24.00000069124155}, 'time': 0.02026510238647461, 'obj': 23.999999916096087, 'status': 'optimal'}
[ 1.00e+00 -1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00]
[-1.00e+00  1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00 -1.00e+00  1.00e+00  1.00e+00  1.00e+00]
[ 1.00e+00 -1.00e+00 

## Real data from themoviedb.com
Extracting  a sub graph of the entire database

In [127]:
# building the summary dictionary
summary_dictionary = build_user_to_movies('movielens.tsv')
# unpacking of the dictionary
users_to_movies = summary_dictionary['users_to_movies']
n_users = summary_dictionary['n_users']
k_users = 4
n_movies = summary_dictionary['n_movies']
k_movies = 4
# building the rating matrix
a = build_a(n_users, k_users, n_movies, k_movies, users_to_movies)
# building the adjacency matrix
W = build_graph(k_users, k_movies, a)
print(W)

[[ 0.   0.   0.   0.   0.   1.   0.   0.1]
 [ 0.   0.   0.   0.   0.   2.5 -1.   0. ]
 [ 0.   0.   0.   0.   1.5  2.5  0.   0. ]
 [ 0.   0.   0.   0.   0.5  2.5  0.5  1.5]
 [ 0.   0.   1.5  0.5  0.   0.   0.   0. ]
 [ 1.   2.5  2.5  2.5  0.   0.   0.   0. ]
 [ 0.  -1.   0.   0.5  0.   0.   0.   0. ]
 [ 0.1  0.   0.   1.5  0.   0.   0.   0. ]]


In [128]:
# the laplacian of the graph
L = build_laplacian(W)
X = solve_sdp(L, triangle_inequalities=True)
X_array=np.array(X)
print(np.round(X_array))
assignement_X = assignment_solution(X_array)
print(assignement_X)

{'cvxopt_sol': {'status': 'optimal', 'primal slack': 2.7709144118761113e-11, 'residual as primal infeasibility certificate': None, 'iterations': 8, 'primal objective': -48.39999996596714, 'primal infeasibility': 2.7763464056982643e-11, 'y': <8x1 matrix, tc='d'>, 'gap': 6.822142655625111e-08, 'z': <2112x1 matrix, tc='d'>, 'x': <36x1 matrix, tc='d'>, 'relative gap': 1.4095336075252391e-09, 'dual infeasibility': 6.227702352967639e-12, 's': <2112x1 matrix, tc='d'>, 'dual slack': 2.0664026079080596e-12, 'residual as dual infeasibility certificate': None, 'dual objective': -48.40000002558021}, 'time': 0.07303714752197266, 'obj': 48.399999995773676, 'status': 'optimal'}
[[ 1.  1.  1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.]
 [ 1.  1.  1.  1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.]]
[ True  True  True  True False False  True Fals

In [105]:
print(np.round(X_array))

[[ 1.  0.  0. -0. -0. -0.]
 [ 0.  1.  0. -0. -0. -0.]
 [ 0.  0.  1. -1. -1. -1.]
 [-0. -0. -1.  1.  1.  1.]
 [-0. -0. -1.  1.  1.  1.]
 [-0. -0. -1.  1.  1.  1.]]
